### ISSUE TITLE
references

### ISSUE THREAD

**Issue by kenzo-tanaka** [kenzo-tanaka/dotfiles#1]
vim基礎
https://qiita.com/jnchito/items/57ffda5712636a9a1e62

dotfile下に入れているだけでは読み込めないのでシンボリックで読み込めるようにする必要があるらしい
(bashとかのコマンドを叩いたときに dotfile 下をみに行く感じかな)
https://qiita.com/massy22/items/5bdb97f8d6e93517f916
https://qiita.com/okamos/items/7f5461814e8ed8916870

**Comment by kenzoukenzou** [comment]
シンボリックとはなんだ

**Comment by kenzoukenzou** [comment]
vim下上へのスクロール
http://vimblog.hatenablog.com/entry/vim_scroll

**Comment by kenzoukenzou** [comment]
[Bashでもpeco使いたい - Qiita](https://qiita.com/omega999/items/8717c1b9d8bc10596d67)

**Comment by kenzo-tanaka** [comment]
[dotfiles/.zshrc at master · ulwlu/dotfiles](https://github.com/ulwlu/dotfiles/blob/master/dotfiles/.zshrc)

**Comment by kenzo-tanaka** [comment]
[bash - How to display $PATH as one directory per line? - Ask Ubuntu](https://askubuntu.com/questions/600018/how-to-display-path-as-one-directory-per-line)

**Comment by kenzo-tanaka** [comment]
パスを通すの意味はだいたいわかった。例えば`cat`コマンドがパスの指定なくコマンドとして呼び出すことができているのは、`ls = /bin/cat` としてパスが通っているからである。
